# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 085e431f673bea20978851d71d3d02a7cd47f5594a6b988e5190192cc5cc90713d02e20ca4c8485b2bb126ab7f82a02ff632db282fb4d216cbd68be037e24507

test:
  secret_key_base: 4b003daa53847aa71559ec54dd4be19d956c9ec9eccf0624094225af5cfd79d2abb040225623e1a46d070d9879d010ccebd416818b95ff01cec19609e8b2a670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
